import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ProBook
 */
public class Admine extends javax.swing.JFrame {
    
        Connection connection;
        PreparedStatement ps;
        PreparedStatement pw;
        DefaultTableModel model = new DefaultTableModel();
        String motpass;

    /**
     * Creates new form Admine
     */
    public Admine() {
        initComponents();
       
    try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
        ps = connection.prepareStatement("SELECT Username, Nom, Prenom, email, id_ad FROM admin");
        ResultSet result = ps.executeQuery();
        while(result.next()){
           ID.setText(result.getString(5));
           NOM.setText(result.getString(2));
           PRENOM.setText(result.getString(3));
           USERNAME.setText(result.getString(1));
           EMAIL.setText(result.getString(4));    
        }
             } 
    catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);   
    }
        
    }
    public void afficher(){
            try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
        ps = connection.prepareStatement("SELECT Username, Nom, Prenom, email, id_ad FROM admin");
        ResultSet result = ps.executeQuery();
        while(result.next()){
           ID.setText(result.getString(5));
           NOM.setText(result.getString(2));
           PRENOM.setText(result.getString(3));
           USERNAME.setText(result.getString(1));
           EMAIL.setText(result.getString(4));     
        }
             } 
    catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);   
    }
    } 
    public static boolean isValidEmailAddress(String email) {
   boolean result = true;
   try {
      InternetAddress emailAddr = new InternetAddress(email);
      emailAddr.validate();
   } catch (AddressException ex) {
      result = false;
   }
   return result;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu_0 = new javax.swing.JLabel();
        menu_1 = new javax.swing.JLabel();
        menu_2 = new javax.swing.JLabel();
        menu_3 = new javax.swing.JLabel();
        menu_5 = new javax.swing.JLabel();
        menu_6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NOM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PRENOM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        edit_1 = new javax.swing.JLabel();
        edit_2 = new javax.swing.JLabel();
        edit_3 = new javax.swing.JLabel();
        edit_4 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        NVMOTPASS = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        MOTPASS = new javax.swing.JPasswordField();
        edit_5 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1083, 735));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 735));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_00.png"))); // NOI18N
        menu_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_0MouseMoved(evt);
            }
        });
        menu_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_0MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_0MouseExited(evt);
            }
        });
        jPanel1.add(menu_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 87, 120, 40));

        menu_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_01RG.png"))); // NOI18N
        menu_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_1MouseMoved(evt);
            }
        });
        menu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_1MouseExited(evt);
            }
        });
        jPanel1.add(menu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 143, 120, 40));

        menu_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_02.png"))); // NOI18N
        menu_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_2.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_2MouseMoved(evt);
            }
        });
        menu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_2MouseExited(evt);
            }
        });
        jPanel1.add(menu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 184, 120, 50));

        menu_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_03.png"))); // NOI18N
        menu_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_3.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_3.setVerifyInputWhenFocusTarget(false);
        menu_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_3MouseMoved(evt);
            }
        });
        menu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_3MouseExited(evt);
            }
        });
        jPanel1.add(menu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 240, 130, 40));

        menu_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_05.png"))); // NOI18N
        menu_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_5MouseMoved(evt);
            }
        });
        menu_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_5MouseExited(evt);
            }
        });
        jPanel1.add(menu_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 291, 150, 40));

        menu_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_06.png"))); // NOI18N
        menu_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_6.setMaximumSize(new java.awt.Dimension(117, 28));
        menu_6.setMinimumSize(new java.awt.Dimension(117, 28));
        menu_6.setPreferredSize(new java.awt.Dimension(117, 28));
        menu_6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_6MouseMoved(evt);
            }
        });
        menu_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_6MouseExited(evt);
            }
        });
        jPanel1.add(menu_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 342, 140, 40));

        jLabel14.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel14.setText("ID :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 100, -1));

        ID.setEnabled(false);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 150, -1));

        NOM.setEnabled(false);
        NOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMActionPerformed(evt);
            }
        });
        jPanel1.add(NOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 150, -1));

        jLabel12.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel12.setText("Nom :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 100, -1));

        jLabel10.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel10.setText("Prenom");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 60, -1));

        EMAIL.setEnabled(false);
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });
        jPanel1.add(EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 150, -1));

        jLabel13.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel13.setText("E-mail ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 100, -1));

        PRENOM.setEnabled(false);
        PRENOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRENOMActionPerformed(evt);
            }
        });
        jPanel1.add(PRENOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 150, -1));

        jLabel3.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel3.setText("Nom Acee :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 110, -1));

        USERNAME.setEnabled(false);
        jPanel1.add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 150, -1));

        jLabel5.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel5.setText("Mot pass");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 110, -1));

        edit_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-1.png"))); // NOI18N
        edit_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_1MouseMoved(evt);
            }
        });
        edit_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_1MouseExited(evt);
            }
        });
        jPanel1.add(edit_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 30, 30));

        edit_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-1.png"))); // NOI18N
        edit_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_2MouseMoved(evt);
            }
        });
        edit_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_2MouseExited(evt);
            }
        });
        jPanel1.add(edit_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 30, 30));

        edit_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-1.png"))); // NOI18N
        edit_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_3MouseMoved(evt);
            }
        });
        edit_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_3MouseExited(evt);
            }
        });
        jPanel1.add(edit_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 30, 30));

        edit_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-1.png"))); // NOI18N
        edit_4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_4MouseMoved(evt);
            }
        });
        edit_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_4MouseExited(evt);
            }
        });
        jPanel1.add(edit_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 30, 30));

        msg.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 424, 70, -1));

        NVMOTPASS.setEnabled(false);
        jPanel1.add(NVMOTPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 150, -1));

        jLabel6.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel6.setText("NV Mot pass");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        MOTPASS.setEnabled(false);
        MOTPASS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MOTPASSMouseClicked(evt);
            }
        });
        jPanel1.add(MOTPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 150, -1));

        edit_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edit_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-1.png"))); // NOI18N
        edit_5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                edit_5MouseMoved(evt);
            }
        });
        edit_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_5MouseExited(evt);
            }
        });
        jPanel1.add(edit_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 30, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png"))); // NOI18N
        logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutMouseMoved(evt);
            }
        });
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 400, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admin.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void menu_0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseMoved
        menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00G.png")));
    }//GEN-LAST:event_menu_0MouseMoved

    private void menu_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseClicked
        Home H = new Home();
        H.setVisible(true); 
        H.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_0MouseClicked

    private void menu_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseExited
        menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00.png")));
    }//GEN-LAST:event_menu_0MouseExited

    private void menu_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseMoved
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01R.png")));
    }//GEN-LAST:event_menu_1MouseMoved

    private void menu_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseExited
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01RG.png")));
    }//GEN-LAST:event_menu_1MouseExited

    private void menu_2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseMoved
        menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02G.png")));
    }//GEN-LAST:event_menu_2MouseMoved

    private void menu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseClicked
        // TODO add your handling code here:
        Materiel M = new Materiel();
        M.setVisible(true);
        M.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_2MouseClicked

    private void menu_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseExited
        menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02.png")));
    }//GEN-LAST:event_menu_2MouseExited

    private void menu_3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseMoved
        menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03G.png")));
    }//GEN-LAST:event_menu_3MouseMoved

    private void menu_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseClicked
        // TODO add your handling code here:
        Utilisateur U = new Utilisateur();
        U.setVisible(true);
        U.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_3MouseClicked

    private void menu_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseExited
        menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03.png")));
    }//GEN-LAST:event_menu_3MouseExited

    private void menu_5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseMoved
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05G.png")));
    }//GEN-LAST:event_menu_5MouseMoved

    private void menu_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseClicked
        // TODO add your handling code here:
        Recherche Re = new Recherche();
        Re.setVisible(true);
        Re.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_5MouseClicked

    private void menu_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseExited
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05.png")));
    }//GEN-LAST:event_menu_5MouseExited

    private void menu_6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseMoved
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06G.png")));
    }//GEN-LAST:event_menu_6MouseMoved

    private void menu_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseExited
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06.png")));
    }//GEN-LAST:event_menu_6MouseExited

    private void NOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMActionPerformed

    private void PRENOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRENOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRENOMActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(NOM.getText().equals("") || PRENOM.getText().equals("") || USERNAME.getText().equals("") || EMAIL.getText().equals("") || String.valueOf(MOTPASS.getPassword()).equals(""))
            {JOptionPane.showMessageDialog(null,"Completé les champs !!");}
      else {
        if(NOM.getText().matches("[a-zA-Z ,]+") && PRENOM.getText().matches("[a-zA-Z ,]+") && isValidEmailAddress(EMAIL.getText())) {  
            
              try {
                connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
                pw = connection.prepareStatement("SELECT * FROM admin WHERE Password = ?"); 
                pw.setString(1, String.valueOf(MOTPASS.getPassword()));
                ResultSet result = pw.executeQuery();
            if(result.next()){   
                    msg.setText(null);
                    if(String.valueOf(NVMOTPASS.getPassword()).equals("")){
                    pw.close();
                    ps = connection.prepareStatement("UPDATE `admin` SET  Username =?, Nom =?, Prenom =?,email =?  WHERE `id_ad`=?");
                    ps.setString(1, USERNAME.getText());
                    ps.setString(2, NOM.getText());
                    ps.setString(3, PRENOM.getText());
                    ps.setString(4, EMAIL.getText());
                    ps.setString(5, ID.getText());
                  if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    ps.executeUpdate();
                    NOM.setEnabled(false);
                    PRENOM.setEnabled(false);
                    USERNAME.setEnabled(false);
                    EMAIL.setEnabled(false);
                    MOTPASS.setText(null);
                    MOTPASS.setEnabled(false);
                    NVMOTPASS.setText(null);
                    NVMOTPASS.setEnabled(false);
                    NVMOTPASS.setEnabled(false);
                    afficher();
                    JOptionPane.showMessageDialog(null,"Les information de L'admine été modifier");
                  }
                 }
            else{
                ps = connection.prepareStatement("UPDATE `admin` SET  Username =?, Nom =?, Prenom =?, email =?, Password =? WHERE `id_ad`=?");
                ps.setString(1, USERNAME.getText());
                ps.setString(2, NOM.getText());
                ps.setString(3, PRENOM.getText());
                ps.setString(4, EMAIL.getText());
                ps.setString(5, String.valueOf(NVMOTPASS.getPassword()));
                ps.setString(6, ID.getText());
                  if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    ps.executeUpdate();
                    NOM.setEnabled(false);
                    PRENOM.setEnabled(false);
                    USERNAME.setEnabled(false);
                    MOTPASS.setText(null);
                    MOTPASS.setEnabled(false);
                    NVMOTPASS.setText(null);
                    NVMOTPASS.setEnabled(false);
                    afficher();
                    JOptionPane.showMessageDialog(null,"Les information de L'admin été modifier");
                  }
                }
            }else{msg.setText("Invalide");}
        
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);}
        
         }else if(!NOM.getText().matches("[a-zA-Z ,]+")){
            JOptionPane.showMessageDialog(null,"Insérer correct Nom ");}
               else if(!PRENOM.getText().matches("[a-zA-Z ,]+")){
            JOptionPane.showMessageDialog(null,"Insérer correct Prenom ");}
               else{
            JOptionPane.showMessageDialog(null,"Insérer correct E-mail ex : exemple@exemple.com ");}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        
    }//GEN-LAST:event_EMAILActionPerformed

    private void edit_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_1MouseMoved
       edit_1.setIcon(new ImageIcon(getClass().getResource("/icons/edit-2.png")));
    }//GEN-LAST:event_edit_1MouseMoved

    private void edit_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_1MouseExited
        edit_1.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_1MouseExited

    private void edit_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_1MouseClicked
        NOM.setEnabled(true);
        MOTPASS.setEnabled(true);
        edit_1.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_1MouseClicked

    private void edit_2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_2MouseMoved
        edit_2.setIcon(new ImageIcon(getClass().getResource("/icons/edit-2.png")));
    }//GEN-LAST:event_edit_2MouseMoved

    private void edit_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_2MouseClicked
        USERNAME.setEnabled(true);
        MOTPASS.setEnabled(true);
        edit_2.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_2MouseClicked

    private void edit_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_2MouseExited
        edit_2.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_2MouseExited

    private void edit_3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_3MouseMoved
        edit_3.setIcon(new ImageIcon(getClass().getResource("/icons/edit-2.png")));
    }//GEN-LAST:event_edit_3MouseMoved

    private void edit_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_3MouseClicked
        EMAIL.setEnabled(true);
        MOTPASS.setEnabled(true);
        edit_3.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_3MouseClicked

    private void edit_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_3MouseExited
        edit_3.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_3MouseExited

    private void edit_4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_4MouseMoved
        edit_4.setIcon(new ImageIcon(getClass().getResource("/icons/edit-2.png")));
    }//GEN-LAST:event_edit_4MouseMoved

    private void edit_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_4MouseClicked
        PRENOM.setEnabled(true);
        MOTPASS.setEnabled(true);
        edit_4.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_4MouseClicked

    private void edit_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_4MouseExited
        edit_4.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_4MouseExited

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void edit_5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_5MouseMoved
        edit_5.setIcon(new ImageIcon(getClass().getResource("/icons/edit-2.png")));
    }//GEN-LAST:event_edit_5MouseMoved

    private void edit_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_5MouseClicked
        NVMOTPASS.setEnabled(true);
        MOTPASS.setEnabled(true);
        edit_5.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_5MouseClicked

    private void edit_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_5MouseExited
        edit_5.setIcon(new ImageIcon(getClass().getResource("/icons/edit-1.png")));
    }//GEN-LAST:event_edit_5MouseExited

    private void MOTPASSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MOTPASSMouseClicked
        msg.setText(null);
    }//GEN-LAST:event_MOTPASSMouseClicked

    private void logoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseMoved
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power-red.png")));
    }//GEN-LAST:event_logoutMouseMoved

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int val=JOptionPane.showConfirmDialog(null, "Voulez-Vous Vraiment Quitter ?");
        if(val==1){

        }else if(val==0){

            Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void menu_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseClicked
        try {
            Desktop.getDesktop().open(new File("D:\\NetBeansProjects\\Gestion_Materiel\\src\\pdf\\Guide.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Admine A = new Admine();
      A.setVisible(true);
      A.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField MOTPASS;
    private javax.swing.JTextField NOM;
    private javax.swing.JPasswordField NVMOTPASS;
    private javax.swing.JTextField PRENOM;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel edit_1;
    private javax.swing.JLabel edit_2;
    private javax.swing.JLabel edit_3;
    private javax.swing.JLabel edit_4;
    private javax.swing.JLabel edit_5;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu_0;
    private javax.swing.JLabel menu_1;
    private javax.swing.JLabel menu_2;
    private javax.swing.JLabel menu_3;
    private javax.swing.JLabel menu_5;
    private javax.swing.JLabel menu_6;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
