import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ProBook
 */
public class ForgotPassword extends javax.swing.JFrame {
    Connection connection;
    PreparedStatement ps;
    private static String USER_NAME = "atman.developer@gmail.com";  // GMail user name (just the part before "@gmail.com")
    private static String PASSWORD = "0626027157callofduty"; // GMail password
     private static String RECIPIENT;

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        email_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PassMessage = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgforgotpassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(400, 260));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 260));

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 260));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 260));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_input.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email_input.setForeground(new java.awt.Color(204, 204, 204));
        email_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        email_input.setText("E-mail");
        email_input.setToolTipText("");
        email_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                email_inputMousePressed(evt);
            }
        });
        email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_inputActionPerformed(evt);
            }
        });
        jPanel2.add(email_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, 30));

        jButton1.setBackground(new java.awt.Color(171, 51, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Envoyer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 30));

        PassMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PassMessage.setForeground(new java.awt.Color(255, 0, 0));
        PassMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(PassMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 370, 20));

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 50, 50));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Veuillez Saisir votre Mail correcte pour Recuperez votre code");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quel est Mon mot de passe ?");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 400, 50));

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 180));

        bgforgotpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Inter.png"))); // NOI18N
        bgforgotpassword.setMinimumSize(new java.awt.Dimension(400, 260));
        bgforgotpassword.setPreferredSize(new java.awt.Dimension(400, 260));
        jPanel2.add(bgforgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_inputActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loading.setIcon(new ImageIcon(getClass().getResource("/icons/ajax-loade-2.gif")));
        jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
        String from = USER_NAME;
        String pass = PASSWORD;
        String subject = "Password for Login to Gestion Materiel app";
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            ps = connection.prepareStatement("SELECT Username, Password , Nom, Prenom FROM admin WHERE email= ? ");
            ps.setString(1, email_input.getText());
            ResultSet result = ps.executeQuery();
               if(result.next()){
                    RECIPIENT = email_input.getText();
                    String[] to = { RECIPIENT }; // list of recipient email addresses
                    String body = " Cher/Chère " +result.getString(3)+" "+result.getString(4)+" Voici votre Nom d'accee : ( " +result.getString(1)+ " ) .  et votre Mot de pass : ( " +result.getString(2)+ " ) .  Pour L'authentification de lapplication de  Gestion de Materiel";
                       if(JOptionPane.showConfirmDialog (null,"Vouler-vous a envoyer votre mot pass a "+email_input.getText(),"confirmation",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                         sendFromGMail(from, pass, to, subject, body,PassMessage,loading);
                         loading.setIcon(null);
                        }
                       else{
                           loading.setIcon(null);
                       }
                    }
               else{
                    loading.setIcon(null);
                    PassMessage.setText("Invalide Email :( !");
                    }
        } catch (SQLException ex) {
            loading.setIcon(null);
            PassMessage.setText("La conexion n'a pas etabli avec la Base :(");
            System.out.println("La conexion n'a pas etabli avec la Base :( ");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButton1.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void email_inputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_inputMousePressed
        PassMessage.setText(null);;
       email_input.setForeground(Color.black);
       String email = email_input.getText();
        if(email.contains("E-mail")){
            email_input.setText(null);
            }
    }//GEN-LAST:event_email_inputMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ForgotPassword F = new ForgotPassword();
        F.setVisible(true);
        F.setLocationRelativeTo(null);
    }
    
    private static void sendFromGMail(String from, String pass, String[] to, String subject, String body,javax.swing.JLabel msg, javax.swing.JLabel ld) {
      
        Properties props = System.getProperties();
        String host = "smtp.gmail.com";
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.user", from);
        props.put("mail.smtp.password", pass);
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");

        Session session = Session.getDefaultInstance(props);
        MimeMessage message = new MimeMessage(session);

        try {
            message.setFrom(new InternetAddress(from));
            InternetAddress[] toAddress = new InternetAddress[to.length];

            // To get the array of addresses
            for( int i = 0; i < to.length; i++ ) {
                toAddress[i] = new InternetAddress(to[i]);
            }

            for( int i = 0; i < toAddress.length; i++) {
                message.addRecipient(Message.RecipientType.TO, toAddress[i]);
            }

            message.setSubject(subject);
            message.setText(body);
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null,"votre mot pass a été  envoyé :) ");
        }
        catch (AddressException ae) {
            ld.setIcon(null);
            msg.setText("Echec d'envoi :( !");
            ae.printStackTrace();
        }
        catch (MessagingException me) {
            ld.setIcon(null);
            msg.setText("Echec d'envoi :( !");
            me.printStackTrace();
        }
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PassMessage;
    private javax.swing.JLabel bgforgotpassword;
    private javax.swing.JTextField email_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loading;
    // End of variables declaration//GEN-END:variables
}
