import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ProBook
 */
public class Login extends javax.swing.JFrame {
     Connection connection;
     PreparedStatement ps;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username_input = new javax.swing.JTextField();
        password_input = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JLabel();
        Login_Message = new javax.swing.JLabel();
        forgotpassword = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        Loginbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1083, 733));
        setMinimumSize(new java.awt.Dimension(1083, 733));
        setPreferredSize(new java.awt.Dimension(1083, 733));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 735));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_input.setForeground(new java.awt.Color(204, 204, 204));
        username_input.setText(" username");
        username_input.setToolTipText("");
        username_input.setBorder(null);
        username_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username_input.setName(""); // NOI18N
        username_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                username_inputMousePressed(evt);
            }
        });
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });
        jPanel1.add(username_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 337, 150, 17));

        password_input.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        password_input.setForeground(new java.awt.Color(204, 204, 204));
        password_input.setEchoChar((char)0);
        password_input.setText(" Mot de Passe");
        password_input.setToolTipText("");
        password_input.setBorder(null);
        password_input.setDoubleBuffered(true);
        password_input.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                password_inputMousePressed(evt);
            }
        });
        password_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_inputActionPerformed(evt);
            }
        });
        jPanel1.add(password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 375, 150, 17));

        loginbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginbtn_2.png"))); // NOI18N
        loginbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        loginbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                loginbtnMouseMoved(evt);
            }
        });
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loginbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginbtnMouseReleased(evt);
            }
        });
        jPanel1.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 408, 90, 32));

        Login_Message.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Login_Message.setForeground(new java.awt.Color(255, 0, 51));
        Login_Message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Login_Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 250, 20));

        forgotpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        forgotpassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotpassword.setText("mot passe oublie ?");
        forgotpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotpassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseMoved(evt);
            }
        });
        forgotpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotpasswordMouseExited(evt);
            }
        });
        jPanel1.add(forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 445, 110, -1));

        loading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 467, 35, 32));

        Loginbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Loginbg.png"))); // NOI18N
        jPanel1.add(Loginbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseMoved
        loginbtn.setIcon(new ImageIcon(getClass().getResource("/icons/Loginbtn_0.png")));
    }//GEN-LAST:event_loginbtnMouseMoved

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        loginbtn.setIcon(new ImageIcon(getClass().getResource("/icons/Loginbtn_2.png")));
    }//GEN-LAST:event_loginbtnMouseExited

    private void loginbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMousePressed
        loginbtn.setIcon(new ImageIcon(getClass().getResource("/icons/Loginbtn_1.png")));  
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ajax-loade-2.gif")));
    }//GEN-LAST:event_loginbtnMousePressed

    private void loginbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseReleased
        loginbtn.setIcon(new ImageIcon(getClass().getResource("/icons/Loginbtn_0.png")));
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ajax-loade-2.gif")));
    }//GEN-LAST:event_loginbtnMouseReleased

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        loading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ajax-loade-2.gif")));
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            ps = connection.prepareStatement("SELECT * FROM admin WHERE Username= ? AND Password = ?");
            ps.setString(1, username_input.getText());
            ps.setString(2, String.valueOf(password_input.getPassword()));
            ResultSet result = ps.executeQuery();
               if(result.next()){
                    Home H = new Home();
                    H.setVisible(true);
                    H.setLocationRelativeTo(null);
                    dispose();
                    }
               else{
                    loading.setIcon(null);
                    Login_Message.setText("Invalide Username or Mot de Pass :(");
                    }
        } catch (SQLException ex) {
            loading.setIcon(null);
            System.out.println("La conexion n'a pas etabli avec la Base");
            Login_Message.setText("La conexion n'a pas etabli avec la Base :( ");
            loading.setIcon(null);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_loginbtnMouseClicked

    private void password_inputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_inputMousePressed
          Login_Message.setText(null);
          password_input.setEchoChar('*');
          password_input.setForeground(Color.black);
          String pass = String.valueOf(password_input.getPassword());
          if(pass.contains(" Mot de Passe")){
            password_input.setText(null);
            }
    }//GEN-LAST:event_password_inputMousePressed

    private void username_inputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_inputMousePressed
       Login_Message.setText(null);
       username_input.setForeground(Color.black);
       String user = username_input.getText();
        if(user.contains(" username")){
            username_input.setText(null);
            }
    }//GEN-LAST:event_username_inputMousePressed

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void password_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_inputActionPerformed

    private void forgotpasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseMoved
        forgotpassword.setForeground(Color.blue);
    }//GEN-LAST:event_forgotpasswordMouseMoved

    private void forgotpasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseExited
        forgotpassword.setForeground(Color.black);
    }//GEN-LAST:event_forgotpasswordMouseExited

    private void forgotpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotpasswordMouseClicked
        ForgotPassword F = new ForgotPassword();
        F.setVisible(true);
        F.setLocationRelativeTo(null);
    }//GEN-LAST:event_forgotpasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       Login l = new Login();
       l.setVisible(true);
       l.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login_Message;
    private javax.swing.JLabel Loginbg;
    private javax.swing.JLabel forgotpassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loginbtn;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
