
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ProBook
 */
public class Materiel extends javax.swing.JFrame {
        Connection connection;
        PreparedStatement ps;
        PreparedStatement pc;
        PreparedStatement pt;
        PreparedStatement pn;
        PreparedStatement pd;
        DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Materiel
     */
 public Materiel() {
        initComponents();
        int i=0;
        String Item;
    try {             
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            ps = connection.prepareStatement("SELECT Nom_Complet FROM utilisateur ");
            ResultSet result = ps.executeQuery();
            while(result.next()){
                //    System.out.println(result.getString(1));
                    id_us.addItem(result.getString(1));
                 }
            }             
    catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }   
                        
    model.addColumn("Référence :");
    model.addColumn("Type :");
    model.addColumn("Etat :");
    model.addColumn("Série :");
    model.addColumn("Utilisateur :");
    model.addColumn("Date d'utilisation :");
    model.addColumn("Date fin d'utilisation :");       
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            ps = connection.prepareStatement("SELECT reference, type_mat, materiel.Serie, utilisateur.Nom_Complet, Date_debut_us, Date_fin_us, Etat "
                                           + "FROM materiel, utilisateur, type "
                                            + "WHERE materiel.Nom_Complet = utilisateur.Nom_Complet AND type.Serie = materiel.Serie ");
            ResultSet result = ps.executeQuery();
                while(result.next()){
                    model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(7),result.getString(3),result.getString(4),
                    result.getString(5),result.getString(6)});
                    }
             } 
        catch (SQLException ex) {
            System.out.println("La conexion n'a pas etabli avec la Base");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        tble.setModel(model);
        
    }
    public void afficher(){
        try {
            model.setRowCount(0);
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            ps = connection.prepareStatement("SELECT reference, type_mat, materiel.Serie,utilisateur.Nom_Complet, Date_debut_us, Date_fin_us, Etat "
                                           + "FROM materiel, utilisateur, type "
                                            + "WHERE materiel.Nom_Complet = utilisateur.Nom_Complet AND type.Serie = materiel.Serie ");
            ResultSet result = ps.executeQuery();
                while(result.next()){
                    model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(7),result.getString(3),result.getString(4),
                    result.getString(5),result.getString(6)});
                    }
             } 
        catch (SQLException ex) {
            System.out.println("La conexion n'a pas etabli avec la Base");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_us = new javax.swing.JComboBox();
        réferenece = new javax.swing.JTextField();
        etat = new javax.swing.JComboBox();
        Inventaire = new javax.swing.JTextField();
        Graphics = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HDD = new javax.swing.JTextField();
        RAM = new javax.swing.JTextField();
        CPU = new javax.swing.JTextField();
        OS = new javax.swing.JTextField();
        série = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        menu_0 = new javax.swing.JLabel();
        menu_1 = new javax.swing.JLabel();
        menu_2 = new javax.swing.JLabel();
        menu_3 = new javax.swing.JLabel();
        menu_5 = new javax.swing.JLabel();
        menu_6 = new javax.swing.JLabel();
        Jdate = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        jSeparator3 = new javax.swing.JSeparator();
        Jdate1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        Mtbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Materiel");
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1083, 733));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 735));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel11.setText("Date d'utilisation :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 435, 130, -1));

        jLabel2.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel2.setText("OS :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 40, -1));

        jLabel3.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel3.setText("Réferenece :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 110, -1));

        jLabel4.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel4.setText("Inventaire :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel5.setText("Type :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        id_us.setBackground(new java.awt.Color(102, 102, 102));
        id_us.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        id_us.setForeground(new java.awt.Color(255, 255, 255));
        id_us.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        id_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_usActionPerformed(evt);
            }
        });
        jPanel1.add(id_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 160, -1));
        jPanel1.add(réferenece, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 160, -1));

        etat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Utilisé", "Reformer", "Inconnu" }));
        etat.setBackground(Color.green);
        etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etatActionPerformed(evt);
            }
        });
        jPanel1.add(etat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 160, -1));
        jPanel1.add(Inventaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 160, -1));

        Graphics.setEnabled(false);
        Graphics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GraphicsActionPerformed(evt);
            }
        });
        jPanel1.add(Graphics, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 60, -1));

        jLabel6.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel6.setText("CPU :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 40, -1));

        jLabel7.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel7.setText("RAM :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 50, -1));

        jLabel8.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel8.setText("HDD :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 50, -1));

        jLabel9.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel9.setText("Graphics :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 90, -1));

        jLabel10.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel10.setText("Série :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 60, -1));

        HDD.setEnabled(false);
        HDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HDDActionPerformed(evt);
            }
        });
        jPanel1.add(HDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 70, -1));

        RAM.setEnabled(false);
        RAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RAMActionPerformed(evt);
            }
        });
        jPanel1.add(RAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 70, -1));

        CPU.setEnabled(false);
        CPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPUActionPerformed(evt);
            }
        });
        jPanel1.add(CPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 60, -1));

        OS.setEnabled(false);
        OS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSActionPerformed(evt);
            }
        });
        jPanel1.add(OS, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 60, -1));

        série.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sérieActionPerformed(evt);
            }
        });
        jPanel1.add(série, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 160, -1));

        jLabel12.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel12.setText("Nom utilisateur :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 130, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 110, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 428, 300, -1));

        menu_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_00.png"))); // NOI18N
        menu_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_0MouseMoved(evt);
            }
        });
        menu_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_0MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_0MouseExited(evt);
            }
        });
        jPanel1.add(menu_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 96, 130, -1));

        menu_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_01.png"))); // NOI18N
        menu_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_1MouseMoved(evt);
            }
        });
        menu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_1MouseExited(evt);
            }
        });
        jPanel1.add(menu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 143, 120, 40));

        menu_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_02RG.png"))); // NOI18N
        menu_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_2.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_2MouseMoved(evt);
            }
        });
        menu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_2MouseExited(evt);
            }
        });
        jPanel1.add(menu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 191, 140, 40));

        menu_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_03.png"))); // NOI18N
        menu_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_3.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_3.setVerifyInputWhenFocusTarget(false);
        menu_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_3MouseMoved(evt);
            }
        });
        menu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_3MouseExited(evt);
            }
        });
        jPanel1.add(menu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 240, 130, 40));

        menu_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_05.png"))); // NOI18N
        menu_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_5MouseMoved(evt);
            }
        });
        menu_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_5MouseExited(evt);
            }
        });
        jPanel1.add(menu_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 291, 160, 40));

        menu_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_06.png"))); // NOI18N
        menu_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_6.setMaximumSize(new java.awt.Dimension(117, 28));
        menu_6.setMinimumSize(new java.awt.Dimension(117, 28));
        menu_6.setPreferredSize(new java.awt.Dimension(117, 28));
        menu_6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_6MouseMoved(evt);
            }
        });
        menu_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_6MouseExited(evt);
            }
        });
        jPanel1.add(menu_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 342, 130, 40));

        Jdate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(Jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 435, 140, 23));

        tble.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "          Référence", "               Type", "               Etat :", "               Série", "           Utilisateur", "     Date d'utilisation", "  Date fin d'utilisation :"
            }
        ));
        tble.setRowHeight(20);
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tble);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 840, 123));

        jLabel13.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel13.setText("Etat :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 60, -1));

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ecran", "Souris", "Clavie", "Unité Centrale" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 215, 160, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 328, 290, -1));

        Jdate1.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(Jdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 465, 140, 23));

        jLabel14.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel14.setText("Date fin d'utilisation :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 467, -1, -1));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png"))); // NOI18N
        logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutMouseMoved(evt);
            }
        });
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 400, 30, 30));

        Mtbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Materiel.png"))); // NOI18N
        jPanel1.add(Mtbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deplace(int i){
       try { 
          réferenece.setText(model.getValueAt (i, 0).toString());
          type.setSelectedItem(model.getValueAt (i, 1).toString());
          etat.setSelectedItem(model.getValueAt (i, 2).toString());
          série.setText(model.getValueAt (i, 3).toString());   
          id_us.setSelectedItem(model.getValueAt (i, 4).toString());
            }
       catch (Exception e)
            { JOptionPane.showMessageDialog(null,"erreur de deplacement de message !!!!! "+e.getMessage());}
            }
    
    private void GraphicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GraphicsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GraphicsActionPerformed

    private void HDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HDDActionPerformed

    private void RAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RAMActionPerformed

    private void CPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPUActionPerformed

    private void OSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OSActionPerformed

    private void sérieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sérieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sérieActionPerformed

    private void menu_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseClicked
        // TODO add your handling code here:
        Home H = new Home();
        H.setVisible(true);
        H.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_0MouseClicked

    private void menu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseClicked
        // TODO add your handling code here:;
    }//GEN-LAST:event_menu_2MouseClicked

    private void menu_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseClicked
        // TODO add your handling code here:
      Utilisateur U = new Utilisateur();
      U.setVisible(true);
      U.setLocationRelativeTo(null);
      dispose();
    }//GEN-LAST:event_menu_3MouseClicked

    private void menu_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseClicked
        // TODO add your handling code here:
        Recherche Re = new Recherche();
        Re.setVisible(true);
        Re.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_5MouseClicked

    private void menu_0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseMoved
        menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00G.png")));
    }//GEN-LAST:event_menu_0MouseMoved

    private void menu_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseExited
        menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00.png")));
    }//GEN-LAST:event_menu_0MouseExited

    private void menu_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseMoved
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01G.png")));
    }//GEN-LAST:event_menu_1MouseMoved

    private void menu_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseExited
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01.png")));
    }//GEN-LAST:event_menu_1MouseExited

    private void menu_2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseMoved
        menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02R.png")));
    }//GEN-LAST:event_menu_2MouseMoved

    private void menu_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseExited
        menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02RG.png")));
    }//GEN-LAST:event_menu_2MouseExited

    private void menu_3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseMoved
        menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03G.png")));
    }//GEN-LAST:event_menu_3MouseMoved

    private void menu_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseExited
        menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03.png")));
    }//GEN-LAST:event_menu_3MouseExited

    private void menu_5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseMoved
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05G.png")));
    }//GEN-LAST:event_menu_5MouseMoved

    private void menu_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseExited
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05.png")));
    }//GEN-LAST:event_menu_5MouseExited

    private void menu_6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseMoved
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06G.png")));
    }//GEN-LAST:event_menu_6MouseMoved

    private void menu_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseExited
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06.png")));
    }//GEN-LAST:event_menu_6MouseExited

    private void menu_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseClicked
      Admine A = new Admine();
      A.setVisible(true);
      A.setLocationRelativeTo(null);
      dispose();
    }//GEN-LAST:event_menu_1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {          
         if(série.getText().equals("") || réferenece.getText().equals("") || ((JTextField)Jdate.getDateEditor().getUiComponent()).getText().equals("") )
           {JOptionPane.showMessageDialog(null,"Completé les champs !!");}
          else  
          {    
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");    
            pd = connection.prepareStatement("SELECT * FROM materiel WHERE `Serie`=?");
            pd.setString(1, série.getText());
            ResultSet result = pd.executeQuery();
          if(result.next()){
            pd.close();
            JOptionPane.showMessageDialog(null," Série est déja attribue pour un autre materiel ");}
          else{                                         
            ps = connection.prepareStatement("INSERT INTO materiel(Serie, reference, Etat, Date_debut_us, Date_fin_us, Nom_Complet) VALUES ( ?, ?, ?, ?, ?, ?)");            
            ps.setString(1, série.getText());
            ps.setString(2, réferenece.getText());
            ps.setString(3, etat.getSelectedItem().toString()); 
            ps.setString(4,((JTextField)Jdate.getDateEditor().getUiComponent()).getText());
            if(((JTextField)Jdate1.getDateEditor().getUiComponent()).getText().equals("")){
                ps.setString(5,null);
            }else{
                 ps.setString(5,((JTextField)Jdate1.getDateEditor().getUiComponent()).getText());}
            ps.setString(6, id_us.getSelectedItem().toString()); 
            ps.executeUpdate();
            
            pt = connection.prepareStatement("INSERT INTO type(id_type, type_mat, Inventaire, Serie) VALUES ( null, ?, ?, ?)");
            pt.setString(1, type.getSelectedItem().toString());
            pt.setString(2, Inventaire.getText());
            pt.setString(3, série.getText());
            pt.executeUpdate(); 
                                     
            if(type.getSelectedItem().toString().contains("Unité Centrale")){
                pc = connection.prepareStatement("INSERT INTO configuration(id_config, OS, CPU, RAM, HDD, Graphics, Serie)  VALUES ( null, ?, ?, ?, ?, ?, ?)");
                pc.setString(1, OS.getText());
                pc.setString(2, CPU.getText());
                pc.setString(3, RAM.getText());
                pc.setString(4, HDD.getText()+" Go");
                pc.setString(5, Graphics.getText());
                pc.setString(6, série.getText());   
                pc.execute();
                OS.setText(null);
                CPU.setText(null);
                RAM.setText(null);
                HDD.setText(null);
                Graphics.setText(null);
                }          
            afficher(); 
            JOptionPane.showMessageDialog(null,"Materiel été ajouter");
            série.setText(null);
            réferenece.setText(null);
            Inventaire.setText(null);           
         }
            }
              
                   
          }                
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"la date est incorrect !");
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
     if(série.getText().equals(""))
           {JOptionPane.showMessageDialog(null,"Selectioner une Materiel !");}  
     else{
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            pd = connection.prepareStatement("SELECT * FROM materiel WHERE `Serie`=?");
            pd.setString(1, série.getText());
            ResultSet result = pd.executeQuery();
            if(result.next()){
            pd.close();
            ps = connection.prepareStatement("DELETE FROM `materiel` WHERE Serie = ?");
            pt = connection.prepareStatement("DELETE FROM `type` WHERE Serie = ?");
            pc = connection.prepareStatement("DELETE FROM `configuration` WHERE Serie = ?");  
                 
            ps.setString(1, série.getText());
            pt.setString(1, série.getText());
            pc.setString(1, série.getText()); 
              if (JOptionPane.showConfirmDialog (null,"Attention vous avez supprimer materiel selection ,est ce que tu et sure ?","supprimer materiel",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {             
                 pc.execute();
                 pt.execute();
                 ps.execute();  
                 série.setText(null);
                 réferenece.setText(null);
                 Inventaire.setText(null);    
                 OS.setText(null);
                 CPU.setText(null);
                 RAM.setText(null);
                 HDD.setText(null);
                    Graphics.setText(null);
                 afficher(); 
                 JOptionPane.showMessageDialog(null,"la Materiel selectioner été supprimer");       
               }
            }
            else{
            JOptionPane.showMessageDialog(null," aucun materiel avec ce Série ");}
            
            } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"la supprission est echo !!!");
            System.out.println(ex.getMessage());
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void id_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_usActionPerformed

    private void etatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etatActionPerformed
        if(etat.getSelectedItem().toString().equals("Utilisé")){
                etat.setBackground(Color.green);
                //Jdate1.setEnabled(false);
        }
        else if(etat.getSelectedItem().toString().equals("Reformer")){
            etat.setBackground(Color.red);      
           // Jdate1.setEnabled(true);
        }
        else{
            etat.setBackground(Color.yellow);
           // Jdate1.setEnabled(true);
        }
    }//GEN-LAST:event_etatActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
     
        if(type.getSelectedItem().toString().equals("Unité Centrale")){
                OS.setEnabled(true);
                RAM.setEnabled(true);
                CPU.setEnabled(true);
                HDD.setEnabled(true);
                Graphics.setEnabled(true);
        }
        else{
                OS.setEnabled(false);
                RAM.setEnabled(false);
                CPU.setEnabled(false);
                HDD.setEnabled(false);
                Graphics.setEnabled(false);
        }
    }//GEN-LAST:event_typeActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try {
            int i = tble.getSelectedRow();
            deplace(i);
            //sa si quant on choisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    private void logoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseMoved
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power-red.png")));
    }//GEN-LAST:event_logoutMouseMoved

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int val=JOptionPane.showConfirmDialog(null, "Voulez-Vous Vraiment Quitter ?");
        if(val==1){

        }else if(val==0){

            Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void menu_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseClicked
        try {
            Desktop.getDesktop().open(new File("D:\\NetBeansProjects\\Gestion_Materiel\\src\\pdf\\Guide.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materiel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Materiel M = new Materiel();
      M.setVisible(true);
      M.setLocationRelativeTo(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPU;
    private javax.swing.JTextField Graphics;
    private javax.swing.JTextField HDD;
    private javax.swing.JTextField Inventaire;
    private com.toedter.calendar.JDateChooser Jdate;
    private com.toedter.calendar.JDateChooser Jdate1;
    private javax.swing.JLabel Mtbg;
    private javax.swing.JTextField OS;
    private javax.swing.JTextField RAM;
    private javax.swing.JComboBox etat;
    private javax.swing.JComboBox id_us;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu_0;
    private javax.swing.JLabel menu_1;
    private javax.swing.JLabel menu_2;
    private javax.swing.JLabel menu_3;
    private javax.swing.JLabel menu_5;
    private javax.swing.JLabel menu_6;
    private javax.swing.JTextField réferenece;
    private javax.swing.JTextField série;
    private javax.swing.JTable tble;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
