
import java.sql.DriverManager;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Phrase;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Cursor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ProBook
 */
public class Utilisateur extends javax.swing.JFrame {
    
        Connection connection;
        PreparedStatement ps;
        PreparedStatement pt;
        DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Utilisateur
     */
    public Utilisateur() {
        initComponents();
        
    model.addColumn("     Nom et Prenom :");
    model.addColumn("          Sérvice :");
    model.addColumn("           Depart :");
    model.addColumn("          N° Etage :");
    
       
    try {
        connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
        ps = connection.prepareStatement("SELECT * FROM utilisateur");
        ResultSet result = ps.executeQuery();
        while(result.next()){
           model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(4),
           result.getString(3)});
        }
             } 
    catch (SQLException ex) {
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        tble.setModel(model);
    }
    public void afficher(){
        try {
            model.setRowCount(0);
        connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
        ps = connection.prepareStatement("SELECT * FROM utilisateur");
        ResultSet result = ps.executeQuery();
        while(result.next()){
           model.addRow(new Object[]{result.getString(1),result.getString(2),result.getString(4),
           result.getString(3)});
        }
             } 
        catch (SQLException ex) {
            System.out.println("La conexion n'a pas etabli avec la Base");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        tble.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        service = new javax.swing.JComboBox();
        etage = new javax.swing.JComboBox();
        depart = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menu_0 = new javax.swing.JLabel();
        menu_1 = new javax.swing.JLabel();
        menu_2 = new javax.swing.JLabel();
        menu_3 = new javax.swing.JLabel();
        menu_5 = new javax.swing.JLabel();
        menu_6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        id_us = new javax.swing.JTextField();
        message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        logout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        utilibg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(1083, 733));
        setMinimumSize(new java.awt.Dimension(1083, 733));
        setPreferredSize(new java.awt.Dimension(1083, 733));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 735));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 735));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel5.setText("Service :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel3.setText("Depart :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 80, -1));

        jLabel4.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel4.setText("Etage :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        service.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "service informatique", "service du personnel", "service de la documentation", "service financier et comptable", "service d’équipement", "service de la procédure normale", "service de procédure accélérée", "service de programmation", "service d’exploitation et du suivi", "service de la législation et de la réglementation", "service de la normalisation des contrats et du contentieux", "service topographique et de vulgarisation", "service des acquisitions et de la gestion du patrimoine", "service des études socio-économiques", "service de l’aménagement et des transports", "service des plans d’aménagements et de développement", "service d’architecture et du schéma d’armature urbaine" }));
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        jPanel1.add(service, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 210, -1));

        etage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        etage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etageActionPerformed(evt);
            }
        });
        jPanel1.add(etage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 90, -1));

        depart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "D.A.F", "D.G.U", "D.A.J.F", "D.E", "S.I", "D.G" }));
        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });
        jPanel1.add(depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 90, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 110, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 110, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 110, -1));

        menu_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_00.png"))); // NOI18N
        menu_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_0.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_0MouseMoved(evt);
            }
        });
        menu_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_0MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_0MouseExited(evt);
            }
        });
        jPanel1.add(menu_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 92, 150, 50));

        menu_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_01.png"))); // NOI18N
        menu_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_1MouseMoved(evt);
            }
        });
        menu_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_1MouseExited(evt);
            }
        });
        jPanel1.add(menu_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 143, 110, 40));

        menu_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_02.png"))); // NOI18N
        menu_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_2.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_2MouseMoved(evt);
            }
        });
        menu_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_2MouseExited(evt);
            }
        });
        jPanel1.add(menu_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 189, 120, 40));

        menu_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_03RG.png"))); // NOI18N
        menu_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_3.setPreferredSize(new java.awt.Dimension(117, 20));
        menu_3.setVerifyInputWhenFocusTarget(false);
        menu_3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_3MouseMoved(evt);
            }
        });
        menu_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_3MouseExited(evt);
            }
        });
        jPanel1.add(menu_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 240, 140, 40));

        menu_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_05.png"))); // NOI18N
        menu_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_5MouseMoved(evt);
            }
        });
        menu_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_5MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_5MouseExited(evt);
            }
        });
        jPanel1.add(menu_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 291, 160, 40));

        menu_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_06.png"))); // NOI18N
        menu_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_6.setMaximumSize(new java.awt.Dimension(117, 28));
        menu_6.setMinimumSize(new java.awt.Dimension(117, 28));
        menu_6.setPreferredSize(new java.awt.Dimension(117, 28));
        menu_6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menu_6MouseMoved(evt);
            }
        });
        menu_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_6MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_6MouseExited(evt);
            }
        });
        jPanel1.add(menu_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 342, 150, 40));

        jLabel13.setFont(new java.awt.Font("Architects Daughter", 1, 11)); // NOI18N
        jLabel13.setText("Nom et Prenom :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 130, -1));

        id_us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_usActionPerformed(evt);
            }
        });
        jPanel1.add(id_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 210, -1));

        message.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message.setForeground(new java.awt.Color(0, 255, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 410, 20));

        tble.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "               Nom :", "             Sérvice", "            N° Etage", "             Depart"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 660, 123));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png"))); // NOI18N
        logout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logoutMouseMoved(evt);
            }
        });
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 400, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(48, 50));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, -1));

        utilibg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Utilisateur.png"))); // NOI18N
        jPanel1.add(utilibg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void deplace(int i){
       try {     
          id_us.setText(model.getValueAt (i, 0).toString());
          service.setSelectedItem(model.getValueAt (i, 1).toString());
          depart.setSelectedItem(model.getValueAt (i, 2).toString()); 
          etage.setSelectedItem(model.getValueAt (i, 3).toString());
          
            }
       catch (Exception e)
            { JOptionPane.showMessageDialog(null,"erreur de deplacement de message !!!!! "+e.getMessage());}
         }
    
    private void menu_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseClicked
        // TODO add your handling code here:
        Home H = new Home();
        H.setVisible(true); 
        H.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_0MouseClicked

    private void menu_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseClicked
        // TODO add your handling code here:
      Materiel M = new Materiel();
      M.setVisible(true);
      M.setLocationRelativeTo(null);
      dispose();
    }//GEN-LAST:event_menu_2MouseClicked

    private void menu_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseClicked
        // TODO add your handling code here:
        Recherche Re = new Recherche();
        Re.setVisible(true);
        Re.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_menu_5MouseClicked

    private void menu_0MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseMoved
       menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00G.png")));
    }//GEN-LAST:event_menu_0MouseMoved

    private void menu_0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_0MouseExited
        menu_0.setIcon(new ImageIcon(getClass().getResource("/icons/menu_00.png")));
    }//GEN-LAST:event_menu_0MouseExited

    private void menu_1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseMoved
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01G.png")));
    }//GEN-LAST:event_menu_1MouseMoved

    private void menu_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseExited
        menu_1.setIcon(new ImageIcon(getClass().getResource("/icons/menu_01.png")));
    }//GEN-LAST:event_menu_1MouseExited

    private void menu_2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseMoved
       menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02G.png")));
    }//GEN-LAST:event_menu_2MouseMoved

    private void menu_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_2MouseExited
        menu_2.setIcon(new ImageIcon(getClass().getResource("/icons/menu_02.png")));
    }//GEN-LAST:event_menu_2MouseExited

    private void menu_3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseMoved
        menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03R.png")));
    }//GEN-LAST:event_menu_3MouseMoved

    private void menu_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_3MouseExited
       menu_3.setIcon(new ImageIcon(getClass().getResource("/icons/menu_03RG.png")));
    }//GEN-LAST:event_menu_3MouseExited

    private void menu_5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseMoved
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05G.png")));
    }//GEN-LAST:event_menu_5MouseMoved

    private void menu_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_5MouseExited
        menu_5.setIcon(new ImageIcon(getClass().getResource("/icons/menu_05.png")));
    }//GEN-LAST:event_menu_5MouseExited

    private void menu_6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseMoved
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06G.png")));
    }//GEN-LAST:event_menu_6MouseMoved

    private void menu_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseExited
        menu_6.setIcon(new ImageIcon(getClass().getResource("/icons/menu_06.png")));
    }//GEN-LAST:event_menu_6MouseExited

    private void menu_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_1MouseClicked
      Admine A = new Admine();
      A.setVisible(true);
      A.setLocationRelativeTo(null);
      dispose();
    }//GEN-LAST:event_menu_1MouseClicked

    private void id_usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_usActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
          if(id_us.getText().equals(""))
           {JOptionPane.showMessageDialog(null,"Remplir tous les champs !");}
          else  
          {     if(id_us.getText().matches("[a-zA-Z ,]+")){
                     connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
                     ps = connection.prepareStatement("INSERT INTO utilisateur(Nom_Complet,Service, N_Etage, Depart) VALUES ( ?, ?, ?, ?)");
                     ps.setString(1, id_us.getText());
                     ps.setString(2, service.getSelectedItem().toString());
                     ps.setString(3, etage.getSelectedItem().toString());
                     ps.setString(4, depart.getSelectedItem().toString());
                     ps.execute();
                     afficher();
                     JOptionPane.showMessageDialog(null,"L'utilisateur été ajouter");
                     id_us.setText(null);     
               }else{
                    JOptionPane.showMessageDialog(null,"Insérer correct Nom et Prenom ");}
             
           }                           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Veuillez changer le Nom et le Prenom par ce que est déja attribue pour un autre utilisateur");
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(id_us.getText().equals(""))
           {JOptionPane.showMessageDialog(null,"Completé les champs !!");}
      else{
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            pt = connection.prepareStatement("SELECT * FROM utilisateur WHERE `Nom_Complet`=?");
            pt.setString(1, id_us.getText());
            ResultSet result = pt.executeQuery();
            if(result.next()){
              pt.close();
              ps = connection.prepareStatement("UPDATE `utilisateur` SET `Service`=?,`N_Etage`=?,`Depart`=? WHERE `Nom_Complet`=?");
              ps.setString(1, service.getSelectedItem().toString());
              ps.setString(2, etage.getSelectedItem().toString());
              ps.setString(3, depart.getSelectedItem().toString());
              ps.setString(4, id_us.getText());
              if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
              ps.executeUpdate();
              id_us.setText(null);
              afficher();
              JOptionPane.showMessageDialog(null,"L'utilisateur été modifier");}
            }
            else{
               JOptionPane.showMessageDialog(null,"aucun utilisateur avec ce nom et prenom"); 
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"erreur de modifier !!!");
            System.out.println(ex);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     if(id_us.getText().equals(""))
           {JOptionPane.showMessageDialog(null,"Selectioner un Utilisateur !!");}  
     else{
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");
            pt = connection.prepareStatement("SELECT * FROM utilisateur WHERE `Nom_Complet`=?");
            pt.setString(1, id_us.getText());
            ResultSet result = pt.executeQuery();
            if(result.next()){
              pt.close();
              ps = connection.prepareStatement("DELETE FROM `utilisateur` WHERE Nom_Complet = ?");
              ps.setString(1, id_us.getText());
              if (JOptionPane.showConfirmDialog (null,"Attention vous avez supprimer l'utilisateur selection ,est ce que tu et sure?"
                     ,"supprimer utilisateur",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                 ps.execute();
                 id_us.setText(null);
                 afficher();
                 JOptionPane.showMessageDialog(null,"L'utilisateur selectioner été supprimer");}
            }
            else{
               JOptionPane.showMessageDialog(null,"aucun utilisateur avec ce nom et prenom");  
            }

             } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"la supprission est echo !!!");
            System.out.println("La conexion n'a pas etabli avec la Base :( ");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try {  
            int i = tble.getSelectedRow();
            deplace(i);
            //sa si quant on choisir un nom dans le tableau il va afficher sur les fieldtext
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur selectionne\n"+e.getMessage());}
    }//GEN-LAST:event_tbleMouseClicked

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departActionPerformed

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serviceActionPerformed

    private void etageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etageActionPerformed

    private void logoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseMoved
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power-red.png")));
    }//GEN-LAST:event_logoutMouseMoved

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        int val=JOptionPane.showConfirmDialog(null, "Voulez-Vous Vraiment Quitter ?");
        if(val==1){

        }else if(val==0){

            Login l = new Login();
            l.setVisible(true);
            l.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/power.png")));
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf-red.png")));
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png")));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR)); 
        Document d=new Document() {};
        try {

            PdfWriter.getInstance(d, new FileOutputStream("D:\\NetBeansProjects\\Gestion_Materiel\\src\\pdf\\Les_Utilisateurs_des_Materiel_Informatique.pdf"));
            d.open();
            com.itextpdf.text.Image im=com.itextpdf.text.Image.getInstance("D:\\NetBeansProjects\\Gestion_Materiel\\src\\icons\\LOGO-2.png");
            im.scaleAbsoluteWidth(200);
            im.scaleAbsoluteHeight(100);
            im.setAlignment(com.itextpdf.text.Image.ALIGN_CENTER);
            d.add(im);

            //Nom de Matier et tous les infos...
            PdfPTable table1=new PdfPTable(1);
            table1.setWidthPercentage(100);
            PdfPCell c;
            c=new PdfPCell(new Phrase("AUL \n",FontFactory.getFont("Comic Sans MS",16,BaseColor.WHITE)));
            c.setHorizontalAlignment(Element.ALIGN_CENTER);
            c.setBorderColor(BaseColor.WHITE);
            c.setBackgroundColor(BaseColor.BLUE);
            table1.addCell(c);
            d.add(table1);
            //souter de ligne
            PdfPTable t=new PdfPTable(1);
            t.setWidthPercentage(100);
            PdfPCell ce;
            ce=new PdfPCell(new Phrase(" Les Utilisateurs des Materiel Informatique \n ",FontFactory.getFont("Comic Sans MS",14,BaseColor.WHITE)));
            ce.setBorderColor(BaseColor.WHITE);
            ce.setHorizontalAlignment(Element.ALIGN_CENTER);
            ce.setBackgroundColor(BaseColor.BLUE);
            t.addCell(ce);
            d.add(t);
            PdfPTable tn=new PdfPTable(1);
            tn.setWidthPercentage(100);
            //souter de ligne
            PdfPTable t1=new PdfPTable(1);
            t1.setWidthPercentage(100);
            PdfPCell ce1;
            ce1=new PdfPCell(new Phrase(" ",FontFactory.getFont("Comic Sans MS",16)));
            ce1.setBorderColor(BaseColor.WHITE);
            ce1.setHorizontalAlignment(Element.ALIGN_CENTER);
            ce1.setBackgroundColor(BaseColor.WHITE);
            t1.addCell(ce1);
            d.add(t1);
            PdfPTable tb=new PdfPTable(4);
            tb.setWidthPercentage(100);
            tb.setHorizontalAlignment(100);
            PdfPCell cell;
            cell=new PdfPCell(new Phrase("Nom et Prenom ",FontFactory.getFont("Comic Sans MS",14)));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            tb.addCell(cell);
            cell=new PdfPCell(new Phrase("Sérvice",FontFactory.getFont("Comic Sans MS",14)));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            tb.addCell(cell);
            cell=new PdfPCell(new Phrase("Departements",FontFactory.getFont("Comic Sans MS",14)));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            tb.addCell(cell);
            cell=new PdfPCell(new Phrase("N° Etage",FontFactory.getFont("Comic Sans MS",14)));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
            tb.addCell(cell);
            d.add(tb);
            String sql=" SELECT * FROM utilisateur ";

            connection = DriverManager.getConnection("jdbc:mysql://localhost/gestion_materiel","root", "");

            ps = connection.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){

                PdfPTable tab1=new PdfPTable(4);
                tab1.setWidthPercentage(100);
                tab1.setHorizontalAlignment(100);
                PdfPCell cell1;
                cell1=new PdfPCell(new Phrase(rs.getString(1),FontFactory.getFont("Times New Roman (Titres CS)",12)));
                cell1.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell1.setBackgroundColor(BaseColor.WHITE);
                tab1.addCell(cell1);
                cell1=new PdfPCell(new Phrase(rs.getString(2),FontFactory.getFont("Times New Roman (Titres CS)",12)));
                cell1.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell1.setBackgroundColor(BaseColor.WHITE);
                tab1.addCell(cell1);
                cell1=new PdfPCell(new Phrase(rs.getString(4),FontFactory.getFont("Times New Roman (Titres CS)",12)));
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setBackgroundColor(BaseColor.WHITE);
                tab1.addCell(cell1);
                cell1=new PdfPCell(new Phrase(rs.getString(3),FontFactory.getFont("Times New Roman (Titres CS)",12)));
                cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
                cell1.setBackgroundColor(BaseColor.WHITE);
                tab1.addCell(cell1);
                
                d.add(tab1);

            } 
            d.close();

            Desktop.getDesktop().open(new File("D:\\NetBeansProjects\\Gestion_Materiel\\src\\pdf\\Les_Utilisateurs_des_Materiel_Informatique.pdf"));

        } catch (BadElementException | IOException ex) {
            JOptionPane.showMessageDialog(null,""+ex.getMessage());
        }catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null,""+ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(Recherche.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf-red-2.png")));
    }//GEN-LAST:event_jLabel1MousePressed

    private void menu_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_6MouseClicked
        try {
            Desktop.getDesktop().open(new File("D:\\NetBeansProjects\\Gestion_Materiel\\src\\pdf\\Guide.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      Utilisateur U = new Utilisateur();
      U.setVisible(true);
      U.setLocationRelativeTo(null);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox depart;
    private javax.swing.JComboBox etage;
    private javax.swing.JTextField id_us;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menu_0;
    private javax.swing.JLabel menu_1;
    private javax.swing.JLabel menu_2;
    private javax.swing.JLabel menu_3;
    private javax.swing.JLabel menu_5;
    private javax.swing.JLabel menu_6;
    private javax.swing.JLabel message;
    private javax.swing.JComboBox service;
    private javax.swing.JTable tble;
    private javax.swing.JLabel utilibg;
    // End of variables declaration//GEN-END:variables
}
